---
- name: Uninstall unnessecary packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: '{{ services_to_disable }}'
  become: true

- name: Stop and disable services
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: no
    state: stopped
  loop: '{{ services_to_disable }}'
  loop_control:
    loop_var: item
  become: true
  ignore_errors: true