- name: Change the default shell to zsh
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh
  become: true

- name: Clone Oh My Zsh repository
  ansible.builtin.git:
    repo: '{{ zsh_git_url }}'
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh'
    force: yes
    update: yes
  become_user: '{{ ansible_user_id }}'

- name: "Link zsh config"
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "~/.zshrc"
    force: yes
    state: link

- name: Clone zsh plugins as git repositories
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
  loop:
    - { repo: '{{ zsh_completion_git_url }}', dest: '{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-completions' }
    - { repo: '{{ zsh_autosuggestion_git_url }}', dest: '{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-autosuggestions' }
    - { repo: '{{ zsh_syntax_git_url }}', dest: '{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-syntax-highlighting' }
  when: not item.dest is exists

# - name: Add line to shell configuration files
#   ansible.builtin.lineinfile:
#     path: '{{ item }}'
#     line: 'source /opt/lalubuntu/aliases'
#     insertafter: EOF
#   with_items:
#     - ~/.zshrc
#     - ~/.bashrc

- name: Clone fzf repository
  ansible.builtin.git:
    repo: '{{ fzf_git_url }}'
    dest: '{{ ansible_env.HOME }}/.fzf'
    depth: 1

- name: Run fzf installation script
  ansible.builtin.shell: "zsh -c '~/.fzf/install --all'"

- name: "Copying aliases"
  file:
    src: "{{ role_path }}/files/.aliases"
    dest: "~/.aliases"
    force: yes
    state: link